USE [omcusttaxqa]
GO
SET IDENTITY_INSERT [dbo].[M_MODULE] OFF
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Dashboard', N'Dashboard', CAST(1.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'dashboard', N'/dashboard', N'Vishal Benade', CAST(N'2021-06-04T12:37:52.283' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:37:52.283' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Data Load', N'Data Load', CAST(2.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'dataload', N'/pasmanualdataload', N'Vishal Benade', CAST(N'2021-06-04T12:38:45.977' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:38:45.977' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'SARS Submission', N'SARS Submission', CAST(3.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'sarssubmission', N'/sarssubmission', N'Vishal Benade', CAST(N'2021-06-04T12:39:09.903' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:39:09.903' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Correspondance', N'Correspondance', CAST(4.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'correspondence', N'/correspondence', N'Vishal Benade', CAST(N'2021-06-04T12:39:32.050' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:39:32.050' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Client Servicing', N'Client Servicing', CAST(5.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'clientservicing', N'/clientservicing', N'Vishal Benade', CAST(N'2021-06-04T12:40:17.637' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:40:17.637' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Reports', N'Reports', CAST(6.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'reports', N'/reports', N'Vishal Benade', CAST(N'2021-06-04T12:40:49.080' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:40:49.080' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Admin', N'Admin', CAST(7.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'admin', N'', N'Vishal Benade', CAST(N'2021-06-04T12:41:06.020' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:41:06.020' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'System Setup', N'System Setup', CAST(7.10 AS Decimal(18, 2)), 7, 1, 1, 1, NULL, NULL, N'Vishal Benade', CAST(N'2021-06-04T12:43:10.977' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:43:10.977' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Manual Data Load', N'Manual Data Load', CAST(7.20 AS Decimal(18, 2)), 7, 1, 1, 1, NULL, N'/manualData', N'Vishal Benade', CAST(N'2021-06-04T12:43:55.980' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:43:55.980' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Source System', N'Source System', CAST(7.11 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/sourcesystem', N'Vishal Benade', CAST(N'2021-06-04T12:46:22.647' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:46:22.647' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Tax Module', N'Tax Module', CAST(7.12 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/taxmodule', N'Vishal Benade', CAST(N'2021-06-04T12:47:05.263' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:47:05.263' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Domain and References', N'Domain and References', CAST(7.13 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/domainReferences', N'Vishal Benade', CAST(N'2021-06-04T12:47:25.600' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:47:25.600' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Messaging Event', N'Messaging Event', CAST(7.15 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/messagingEvent', N'Vishal Benade', CAST(N'2021-06-04T12:48:13.807' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:48:13.807' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Notification Configuration', N'Notification Configuration ', CAST(7.14 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/notificationConfig', N'Vishal Benade', CAST(N'2021-06-04T12:49:48.520' AS DateTime), N'Vishal Benade', CAST(N'2021-06-04T12:49:48.520' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'User Management', N'User Management', CAST(8.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'usermanagement', N'/usermanagement', N'Vishal Benade', CAST(N'2021-06-08T12:02:44.600' AS DateTime), N'Vishal Benade', CAST(N'2021-06-08T12:02:44.600' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Submitting Entity', N'Submitting Entity', CAST(7.16 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/submittingEntity', N'Vishal Benade', CAST(N'2021-06-17T05:11:39.627' AS DateTime), N'Vishal Benade', CAST(N'2021-06-17T05:11:39.627' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Fund Entity', N'Fund Entity', CAST(7.17 AS Decimal(18, 2)), 8, 1, 1, 1, NULL, N'/fundEntity', N'Vishal Benade', CAST(N'2021-06-17T05:13:38.917' AS DateTime), N'Vishal Benade', CAST(N'2021-06-17T05:13:38.917' AS DateTime))
GO
INSERT [dbo].[M_MODULE] (  [module_name], [module_description], [display_seq], [parent_module_id], [default_access_flag], [show_in_menu_flag], [status_flag], [image_name], [routes], [created_by], [created_date], [last_updated_by], [last_updated_date]) VALUES ( N'Logout', N'Logout', CAST(9.00 AS Decimal(18, 2)), NULL, 1, 1, 1, N'logout', NULL, N'Vishal Benade', CAST(N'2021-09-08T00:00:00.000' AS DateTime), N'Vishal Benade', CAST(N'2021-09-08T00:00:00.000' AS DateTime))
GO