using System;
using System.Collections.Generic;

namespace OLDMutual.CTS.ManualDataLoad.Domain.Models
{
	public class StgClientGcsResponse
	{
		public int row_id { get; set; }
		public string ERRMSG { get; set; }
		public string ERRFIELD { get; set; }
		public string RETURN_CODE { get; set; }
		public string IN_PARTY_REF { get; set; }
		public string IN_SYSTEM_ID { get; set; }
		public string CP_RELATIONSHIP { get; set; }
		public string CP_PERCENTAGE { get; set; }
		public string PARENT_PARTY_REF { get; set; }
		public string PARENT_SYSTEM_ID { get; set; }
		public string EXT_PARTY_REF { get; set; }
		public string EXT_SYSTEM_ID { get; set; }
		public string GCS_PARTY_REF { get; set; }
		public string GCS_SYSTEM_ID { get; set; }
		public string TITLE { get; set; }
		public string FNAME { get; set; }
		public string NAME { get; set; }
		public string INITIALS { get; set; }
		public string PARTY_TYPE { get; set; }
		public string TYPE_OF_ORG { get; set; }
		public string ORG_TYPE_CODE { get; set; }
		public string GIIN_NO { get; set; }
		public string FATCA_REPORTING_CODE { get; set; }
		public string ROLE { get; set; }
		public string BIRTH_DATE { get; set; }
		public string DEATH_DATE { get; set; }
		public string NAT_ID_NO_1 { get; set; }
		public string ID_NO_TYPE_1 { get; set; }
		public string ID_COUNTRY_1 { get; set; }
		public string NAT_ID_NO_2 { get; set; }
		public string ID_NO_TYPE_2 { get; set; }
		public string ID_COUNTRY_2 { get; set; }
		public string NAT_ID_NO_3 { get; set; }
		public string ID_NO_TYPE_3 { get; set; }
		public string ID_COUNTRY_3 { get; set; }
		public string NAT_ID_NO_4 { get; set; }
		public string ID_NO_TYPE_4 { get; set; }
		public string ID_COUNTRY_4 { get; set; }
		public string NAT_ID_NO_5 { get; set; }
		public string ID_NO_TYPE_5 { get; set; }
		public string ID_COUNTRY_5 { get; set; }
		public string SEX { get; set; }
		public string CO_NO { get; set; }
		public string PREF_LANG { get; set; }
		public string MARITAL_STAT { get; set; }
		public string TAX_REG_NO_1 { get; set; }
		public string TAX_REG_NO_COUNTRY_1 { get; set; }
		public string RESIDENT_MKR_1 { get; set; }
		public string TAX_REG_NO_2 { get; set; }
		public string TAX_REG_NO_COUNTRY_2 { get; set; }
		public string RESIDENT_MKR_2 { get; set; }
		public string TAX_REG_NO_3 { get; set; }
		public string TAX_REG_NO_COUNTRY_3 { get; set; }
		public string RESIDENT_MKR_3 { get; set; }
		public string TAX_REG_NO_4 { get; set; }
		public string TAX_REG_NO_COUNTRY_4 { get; set; }
		public string RESIDENT_MKR_4 { get; set; }
		public string TAX_REG_NO_5 { get; set; }
		public string TAX_REG_NO_COUNTRY_5 { get; set; }
		public string RESIDENT_MKR_5 { get; set; }
		public string COUNTRY_OF_NATIONALITY { get; set; }
		public string ADDRESS_USAGE_1 { get; set; }
		public string START_DATE_1 { get; set; }
		public string ADDRESS_LINE1_1 { get; set; }
		public string ADDRESS_LINE2_1 { get; set; }
		public string ADDRESS_LINE3_1 { get; set; }
		public string ADDRESS_LINE4_1 { get; set; }
		public string POST_CDE_1 { get; set; }
		public string COUNTRY_CODE_1 { get; set; }
		public string CP_STATUS_1 { get; set; }
		public string UPDATED_DATE_1 { get; set; }
		public string ADDRESS_USAGE_2 { get; set; }
		public string START_DATE_2 { get; set; }
		public string ADDRESS_LINE1_2 { get; set; }
		public string ADDRESS_LINE2_2 { get; set; }
		public string ADDRESS_LINE3_2 { get; set; }
		public string ADDRESS_LINE4_2 { get; set; }
		public string POST_CDE_2 { get; set; }
		public string COUNTRY_CODE_2 { get; set; }
		public string CP_STATUS_2 { get; set; }
		public string UPDATED_DATE_2 { get; set; }
		public string ADDRESS_USAGE_3 { get; set; }
		public string START_DATE_3 { get; set; }
		public string ADDRESS_LINE1_3 { get; set; }
		public string ADDRESS_LINE2_3 { get; set; }
		public string ADDRESS_LINE3_3 { get; set; }
		public string ADDRESS_LINE4_3 { get; set; }
		public string POST_CDE_3 { get; set; }
		public string COUNTRY_CODE_3 { get; set; }
		public string CP_STATUS_3 { get; set; }
		public string UPDATED_DATE_3 { get; set; }
		public string ADDRESS_USAGE_4 { get; set; }
		public string START_DATE_4 { get; set; }
		public string ADDRESS_LINE1_4 { get; set; }
		public string ADDRESS_LINE2_4 { get; set; }
		public string ADDRESS_LINE3_4 { get; set; }
		public string ADDRESS_LINE4_4 { get; set; }
		public string POST_CDE_4 { get; set; }
		public string COUNTRY_CODE_4 { get; set; }
		public string CP_STATUS_4 { get; set; }
		public string UPDATED_DATE_4 { get; set; }
		public string ADDRESS_USAGE_5 { get; set; }
		public string START_DATE_5 { get; set; }
		public string ADDRESS_LINE1_5 { get; set; }
		public string ADDRESS_LINE2_5 { get; set; }
		public string ADDRESS_LINE3_5 { get; set; }
		public string ADDRESS_LINE4_5 { get; set; }
		public string POST_CDE_5 { get; set; }
		public string COUNTRY_CODE_5 { get; set; }
		public string CP_STATUS_5 { get; set; }
		public string UPDATED_DATE_5 { get; set; }
		public string CP_USAGE_1 { get; set; }
		public string CP_DETAIL_1 { get; set; }
		public string COUNTRY_DIALING_CODE_1 { get; set; }
		public string CNTRY_CODE_1 { get; set; }
		public string CP_STATUS2_1 { get; set; }
		public string UPDATED_DATE2_1 { get; set; }
		public string CP_USAGE_2 { get; set; }
		public string CP_DETAIL_2 { get; set; }
		public string COUNTRY_DIALING_CODE_2 { get; set; }
		public string CNTRY_CODE_2 { get; set; }
		public string CP_STATUS2_2 { get; set; }
		public string UPDATED_DATE2_2 { get; set; }
		public string CP_USAGE_3 { get; set; }
		public string CP_DETAIL_3 { get; set; }
		public string COUNTRY_DIALING_CODE_3 { get; set; }
		public string CNTRY_CODE_3 { get; set; }
		public string CP_STATUS2_3 { get; set; }
		public string UPDATED_DATE2_3 { get; set; }
		public string CP_USAGE_4 { get; set; }
		public string CP_DETAIL_4 { get; set; }
		public string COUNTRY_DIALING_CODE_4 { get; set; }
		public string CNTRY_CODE_4 { get; set; }
		public string CP_STATUS2_4 { get; set; }
		public string UPDATED_DATE2_4 { get; set; }
		public string CP_USAGE_5 { get; set; }
		public string CP_DETAIL_5 { get; set; }
		public string COUNTRY_DIALING_CODE_5 { get; set; }
		public string CNTRY_CODE_5 { get; set; }
		public string CP_STATUS2_5 { get; set; }
		public string UPDATED_DATE2_5 { get; set; }
		public string CP_USAGE_6 { get; set; }
		public string CP_DETAIL_6 { get; set; }
		public string COUNTRY_DIALING_CODE_6 { get; set; }
		public string CNTRY_CODE_6 { get; set; }
		public string CP_STATUS2_6 { get; set; }
		public string UPDATED_DATE2_6 { get; set; }
		public string EM_USAGE_1 { get; set; }
		public string EM_DETAIL_1 { get; set; }
		public string EM_STATUS_1 { get; set; }
		public string UPDATED_DATE3_1 { get; set; }
		public string EM_USAGE_2 { get; set; }
		public string EM_DETAIL_2 { get; set; }
		public string EM_STATUS_2 { get; set; }
		public string UPDATED_DATE3_2 { get; set; }
		public string PARTY_TYPE_SYS { get; set; }
		public string TYPE_OF_ORG_SYS { get; set; }
		public string EXT_SYSTEM_ID_SYS { get; set; }
		public string ORG_INCEPTION_DATE { get; set; }
		public string TRADING_NAME { get; set; }
		public string CNTRY_TAX_RESID_1 { get; set; }
		public string CNTRY_TAX_START_DATE_1 { get; set; }
		public string CNTRY_TAX_END_DATE_1 { get; set; }
		public string CNTRY_TAX_RESID_2 { get; set; }
		public string CNTRY_TAX_START_DATE_2 { get; set; }
		public string CNTRY_TAX_END_DATE_2 { get; set; }
		public string CNTRY_TAX_RESID_3 { get; set; }
		public string CNTRY_TAX_START_DATE_3 { get; set; }
		public string CNTRY_TAX_END_DATE_3 { get; set; }
		public string CNTRY_TAX_RESID_4 { get; set; }
		public string CNTRY_TAX_START_DATE_4 { get; set; }
		public string CNTRY_TAX_END_DATE_4 { get; set; }
		public string CNTRY_TAX_RESID_5 { get; set; }
		public string CNTRY_TAX_START_DATE_5 { get; set; }
		public string CNTRY_TAX_END_DATE_5 { get; set; }
		public string DWT_COUNTRY { get; set; }
		public string DWT_DTA_RATE { get; set; }
		public string DWT_START_DATE { get; set; }
		public string DWT_END_DATE { get; set; }
		public string IWT_COUNTRY { get; set; }
		public string IWT_DTA_RATE { get; set; }
		public string IWT_START_DATE { get; set; }
		public string IWT_END_DATE { get; set; }
		public string LDT_EXEMPT_MKR { get; set; }
		public string LDT_EXEMPT_CODE { get; set; }
		public string LDT_EXEMPT_DATE { get; set; }
		public string IWT_EXEMPT_MKR { get; set; }
		public string IWT_EXEMPT_CODE { get; set; }
		public string IWT_EXEMPT_DATE { get; set; }
		public string MONEY_LAUND_RISK { get; set; }
		public string CORRESPOND_PREF { get; set; }
		public string NICKNAME { get; set; }
		public string RACE { get; set; }
		public int import_status { get; set; }
		public string import_error { get; set; }
		public int file_id { get; set; }
		public int status_code { get; set; }
		public int batch_id { get; set; }
		public int job_id { get; set; }
		public bool status_flag { get; set; }
		public DateTime created_date { get; set; }
		public DateTime last_updated_date { get; set; }
		public string created_by { get; set; }
		public string last_updated_by { get; set; }
		public int page { get; set; }
		public int size { get; set; }
		public int totalrows { get; set; }

	}
	public class ListGcsResponseData
	{
		public List<StgClientGcsResponse> Gdata { get; set; }
	}
}
